---
# tasks file for roles/nginx
- name: Install nginx
  yum: name=nginx state=latest

- name: Start and enable nginx
  service: name=nginx state=started enabled=true

- name: Update index file
  template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
  notify: Restart nginx
